### ISSUE TITLE
.NET Core Support

### ISSUE THREAD

**Issue by mistakenot** [Zaid-Ajaj/Fable.Remoting#1]
It would be great to see this running on .NET Core. What do you think would be the main challenges in getting this working?

I'm learning F# myself at the moment and looking for a project to contribute to. If it is within my capabilities I'd like to help.

**Comment by Zaid-Ajaj** [comment]
@mistakenot Running on .NET Core is a matter of compiling the code to target netcoreapp1.6 which I wasn't able to do (or rather did not have much time to dig into the issue). 

The problem I came across was that the dotnet core compiler wasn't happy with using `dynamic` and System.Reflection in the `Fable.Remoting.Reflection` project, this is a csharp project that `Fable.Remoting.Suave` depends on. 

I did however compile the code targetting `netcoreapp2.0` which you can find at nuget:
```
// both targeting dotnet 2.0
Fable.Remoting.Reflection
Fable.Remoting.Suave.Core
```
But did not test it properly

You could either try to port the project to netcoreapp1.6 or just create an example project (suave server + fable client) using the library since you are learning F#, your help is highly appreciated :smile:

**Comment by Zaid-Ajaj** [comment]
Never mind, it actually works on .NET Core:
![suave-remoting](https://user-images.githubusercontent.com/13316248/26991454-a4fa2fd2-4d5a-11e7-996c-c06ac2423c91.png)

**Comment by mistakenot** [comment]
Cool, I'll take a look at a sample project.
