### ISSUE TITLE
Enable IServer as interface

### ISSUE THREAD

**Issue by humhei** [Zaid-Ajaj/Fable.Remoting#113]
![image](https://user-images.githubusercontent.com/25994449/54663580-b0ddbc80-4b1c-11e9-8fd7-68a30eac2332.png)

Why?
IMO named parameters is important when communicate between server and client

In my use case:
ExcelDna can read named parameters functions from interface

**Comment by humhei** [comment]
Just read sourcecodes... 
Seems this is breaking change which is hard to implemented

**Comment by Zaid-Ajaj** [comment]
Hello @humhei, this is actually a duplicate of [Hard to use APIs due to lack of parameter names](https://github.com/Zaid-Ajaj/Fable.Remoting/issues/100).

Let me break down why I didn't implement this and why I think it is not a good idea

### Interfaces are erased 
The technical difficulty is primarily due to the fact that interfaces are *erased* at compile time on the client side of things because interfaces are used for interop in Fable. This makes it impossible for `Remoting.Client` to build a proxy without reflection metadata

### Too many opinions
Having two ways of doing the same thing, i.e. defining protocols where records already work really well. I don't want people to think too much of whether they use an interface or a record. 

### Alternatives for named paramteres
Simply use a record for all inputs or use single case unions for names parameters:
```fs
type EvalParams = { code: string; input: string }

type IServer = 
  { eval : EvalParams -> Async<string> 
    test : unit -> Async<unit> }
```
Use single case unions:
```fs
type Code = Code of string
type Input = Input of string

type IServer = 
  { eval :  Code * Input -> Async<string> 
    test : unit -> Async<unit> }

// build proxy
let server = (* . . . *)

// use proxy
server.eval (Code "() => 5", Input "()")
```

Hope this helps

**Comment by humhei** [comment]
Thanks.
Good workaround for me
Get it 😄
