### ISSUE TITLE
json serialization is relatively expensive

### ISSUE THREAD

**Issue by 0x53A** [Zaid-Ajaj/Fable.Remoting#127]
Hi @Zaid-Ajaj , it's me again :D

I have a remoting api that returns an object graph with a lot of little objects.

![image](https://user-images.githubusercontent.com/4236651/62150770-19288000-b2ff-11e9-8bad-fd0214acb376.png)

Of the total time spent, 5% is my (non-trivial) processing, 95% is json serialization. The total duration is about 10 seconds.

Looking at the lower table shows the possible big wins:

I assume the 11% of ``UnionCaseInfo.get_Name`` could be halved to 5% by just caching ``uci,Name`` into a local.

![image](https://user-images.githubusercontent.com/4236651/62151075-d1eebf00-b2ff-11e9-9716-6e3ca37d72ac.png)

The much bigger win would be speeding up / replacing ``GetUnionFields``.

Maybe be ``UnionCaseInfo`` could be cached, and then the fields could be read by accessing the ``PropertyInfo``s:

```f#
[<Sealed>]
type UnionCaseInfo =
class
// ...
member this.GetFields : unit -> PropertyInfo []
// ...
end
```

Anyway, at the moment this is just idle speculation. I'll see if I can create some benchmark over the next few weeks and a PR, but I really need a vacation tbh.

What do you think? Would such a caching approach make sense?

**Comment by Zaid-Ajaj** [comment]
Hello there, 

Thanks for the detailed report! It would be great to have JSON benchmarks :rocket: preferably in a separate repository and a clone of Fable.Remoting.Json with changes made to it so we can see how they compare to each other instead of starting to mess with the code here with prototypes. 

Do you have a type you can share here with a lot of nested records / fields that generates a 8-10 second delay just for serialization?

At a first naive glance, it looks like the solution could be applying memoization against `GetUnionFields` using equality on the input type, but like you said, this is still speculative. 

> but I really need a vacation tbh.

Yeah me too, man 🏖 

> Would such a caching approach make sense?

I am honestly not sure but it is worth the try, in the past I've tried some caching techniques but didn't yield significant results, I guess we have to test things and look at the benchmark results first

**Comment by 0x53A** [comment]
> Do you have a type you can share here with a lot of nested records / fields that generates a 8-10 second delay just for serialization?

https://github.com/0x53A/FableRemotingSerializationTest

It isn't much of a benchmark (yet).

I dumped an object from my dev environment and copied all the type definitions into a new project.

The json is about 5 MB.


![image](https://user-images.githubusercontent.com/4236651/62157452-7dead700-b30d-11e9-9613-9125db42dc62.png)

**Comment by Zaid-Ajaj** [comment]
Thanks for the repro, it looks good and I will try it out soon 👌
