### ISSUE TITLE
How to pick up correct URL with an Azure Web App virtual application?

### ISSUE THREAD

**Issue by markpattison** [Zaid-Ajaj/Fable.Remoting#155]
I'm using Saturn (pretty much a standard SAFE-Stack setup) and deploying to an Azure web app.  I'm struggling to get the client to call the correct API address when I deploy to a virtual application.

For example, assuming the web app is at `www.appname.com`, then the virtual application is at `www.appname.com/virtualappname`.

The API is therefore at `www.appname.com/virtualappname/api/ISomeApi/` and is working correctly.  However, the client is calling `www.appname.com/api/ISomeApi/` and is getting 404 errors as a result.

Everything works running locally, so I'd rather not hard-code the virtual application name into the routes if possible.

Any suggestions appreciated - thanks!

**Comment by Zaid-Ajaj** [comment]
Hello @markpattison, I had this problem ever since I started using Fable.Remoting and the solution is quite simple: check out [this setup](https://github.com/Zaid-Ajaj/SAFE.Simplified/blob/master/client/src/Server.fs) which normalizes the path based during production based on the virtual path of the host.

**Comment by markpattison** [comment]
Brilliant, thanks!  Although I'm embarrassed to see it's been in the SAFE template for over a year and I hadn't noticed...
