### ISSUE TITLE
extensibility point to handle fallback (or even override?) on serialization/deserialization

### ISSUE THREAD

**Issue by smoothdeveloper** [Zaid-Ajaj/Fable.Remoting#205]
cc: @kerams

I made #203 which hack support for System.Data.DataTable between a dotnet server and client (no fable involved) and thought that the library may enable extending to client code, support for adhoc serialization and deserialization of types that fall into the "can't serialize {typename}" case.

in terms of additional state needed, probably those approaches:

if you allow registering type by type, It would probably require some deterministic sorting of polymorphic hierarchy of the types to call custom handlers before or after some other specialized handler

```fsharp
|> Remoting.addTypeHandler<MyType> 
        (fun context -> context.write (*...*))
        (fun context -> context.read  (*...*))
```

the other approach is to handle `obj` to the client code handler, which does the searching (I'm not sure of the context surface needed for client code to provide relevant serialization/deserialization handlers).

```fsharp
|> Remoting.addFallbackTypeHandler 
        (fun context (o:obj) -> match o with :? MyType -> (...)) 
        (fun context -> if context.RequestedType.IsInstanceOf typeof<MyType> then (...))
```

I don't know what the implementation leans towards the most or if it makes sense to open the library like this.

**Comment by kerams** [comment]
You'd need a read/write function pair on both server and client side. Then there's the question of which serialization type you're handling -- the server can send either JSON or MsgPack responses, but currently accepts only JSON. From MsgPack's side this should be straightforward since you're going to be writing/reading a bunch of bytes to/from Stream/ResizeArray using the provided functions. However, I'm not too familiar with SimpleJson and whether you could easily plug in handlers this way, but Zaid with surely chime in on that.

> if it makes sense to open the library like this.

Yeah, I'm not convinced of the benefits this brings to the table either. We can always hardwire some other common BCL types, plus you can always map whatever it is you want to transport to/from a record or collection, which is a bit of an overhead, sure, but you're not exactly stuck in a dead end.

**Comment by Zaid-Ajaj** [comment]
There are two main reasons why this is approach isn't implemented. First of all, it goes against the idea of the library to *not think about data transport*: use the library and 99-100% of what you need will be implemented, tested and tested even more across the platforms. Giving the ability to extend type mappers is like telling users to overthink and over engineer something that is otherwise easier to do by using intermediate common types down to the `byte[]` primitive as @kerams suggested, when needed. 

The second reason is technical complexity and feasibility: complex because you now have to generalize the Json/MsgPack converters and make SimpleJson on the client support the same type conversions which is a lot of time not feasible because of the limited number of BCL types that Fable supports (e.g. DataTable and DataSet). I would rather keep this already-somewhat-complicated set of libraries as simple as possible.

That's why I don't think I will ever want to implement this extensibility model, even though I know every library author wants to make their libraries as generic and as configurable as possible, it won't really help here IMO.

**Comment by Zaid-Ajaj** [comment]
@smoothdeveloper I will be closing this since the discussion is resolved and the specific issue (DataTable/DataSet support) has been fixed and added to the library :smile:
