### ISSUE TITLE
How to make GET requests

### ISSUE THREAD

**Issue by MargaretKrutikova** [Zaid-Ajaj/Fable.Remoting#210]
I apologise if I missed it somewhere in the docs, but is there a way to make GET requests?
It seems like all requests end up as POST and I can't seem to find a way to configure it.
Thanks! 🙂

**Comment by Zaid-Ajaj** [comment]
No worries, it is a little bit hard to find because configuring GET/POST requests happens automatically based on the remote function definitions, see [Raw Http](https://zaid-ajaj.github.io/Fable.Remoting/src/raw-http.html) to learn more. Essentially, when you have a route:
```fs
getData : unit -> Async<Data>
```
or 
```fs
getData : Async<Data>
```
Then the underlying HTTP route will use `GET` HTTP verb, for all other functions, a `POST` request is used

**Comment by MargaretKrutikova** [comment]
So if following REST conventions I want to query, say, all products under a category with `/category/%categoryName/products`, there is no way to convert it to GET?

**Comment by Zaid-Ajaj** [comment]
That is correct, REST conventions aren't followed in this library. Using Giraffe on its own might be the better choice for you if you care about the details of the HTTP transport

**Comment by MargaretKrutikova** [comment]
Yes, thanks for clarifying 🙂 I am still trying to understand how everything hangs together, but it makes sense that the point of the library is that you don't need to worry about the underlying details, instead of trying to follow the rest api conventions.
