### ISSUE TITLE
Handle errors with Result instead of exceptions

### ISSUE THREAD

**Issue by MargaretKrutikova** [Zaid-Ajaj/Fable.Remoting#211]
From what I understand from the docs, it is possible to handle exceptions propagated from the underlying functions and return custom errors to the client.
However, all my service functions return `Async<'a, CustomError>` and I would like to process errors the same way I would do if I were to use `Giraffe` without `Remoting`, where I have control over what status code and json I return from my endpoints.
Is it possible to achieve something similar with `Remoting`?

**Comment by Zaid-Ajaj** [comment]
Hi @MargaretKrutikova, from what I understood, there are two issues at hand (please correct me if I am wrong):
 - Using `Result` with `Async` when returning either data or custom errors 
 - Controlling the returned status code and generated JSON

The first one is easy: just make sure you return `Async<Result<'a, CustomError>>` from the remoting functions 

The second issue however, is not possible with Fable.Remoting. The idea behind the library is that it abstracts away HTTP, Json and Routing and let's call backend functions from the Fable or dotnet client directly

```fs
let backend = 
  Remoting.createApi()
  |> Remoting.buildProxy<IServerApi>

async {
  let! response = backend.getData()
  // do something with response
}
```
Status codes, JSON and routing are all handled under the hood so that you don't care about them. See [Raw Http]() to learn how the routes are generated. Basically:
 - GET routes from `unit -> Async<'t>` or `Async<'t>` functions
 - POST routes from all other functions that accept some input
 - 200 OK status code for all successful functions *that did not throw an exception*
 - 500 Internal Server Error code when a remoting function throws an exception that isn't catched

Those rules are automatically derived from the route definitions and currently there is no way to configure them because that is not what the library was made for :smile:

**Comment by MargaretKrutikova** [comment]
Hi @Zaid-Ajaj ! Thanks for your response 🙂
So If I return `Async<Result<'a, CustomError>>` and it returns an error when the function is called, will the api return error response with an error code?
Can the library handle validation errors as 400 Bad Request?

**Comment by Zaid-Ajaj** [comment]
The library itself does not look at the data to determine which status code should be returned. It sounds like you want to build a standard REST API with proper status codes. In that case, Fable.Remoting might not be a good choice for you because this library lets you forget about the underlying HTTP transport and only think in terms of stateless functions: exposing a standard REST API from the definition is not possible here

> ps: closed the issue by mistake

**Comment by MargaretKrutikova** [comment]
Oh, yes, that makes sense 🙂
I just tried returning `Async<Result<..>>` from my remoting functions, but it doesn't seem to work, and I get a console error:
`Uncaught Error: Expected field create to have a return type of Async<'t>`, am I doing something wrong or is it not supported yet?

**Comment by Zaid-Ajaj** [comment]
Can you please share how the protocol type looks like?

**Comment by MargaretKrutikova** [comment]
I think my environment was acting out and I didn't see the actual compile error 😆 

It does work returning a result type and handling errors on the client, even though it returns http code 200 and the serialized error object in the body, and not 400 as per REST conventions. On the other hand, that's how GraphQL apis handle errors too, so that doesn't seem to be a problem. I think everything works nicely now, thanks a lot for clarifying! 🙂

**Comment by Zaid-Ajaj** [comment]
> I think everything works nicely now, thanks a lot for clarifying! 

No problem, glad to hear it is working for you!
