### ISSUE TITLE
Integration tests doc removed

### ISSUE THREAD

**Issue by OnurGumus** [Zaid-Ajaj/Fable.Remoting#310]
I have seen, you removed integration tests from the new docs. But then how do you do them without proxy? CreateApi always asks for a base url.

**Comment by Zaid-Ajaj** [comment]
Hi there @OnurGumus, indeed I removed the docs but will add them back one-by-one because I wanted to revise them thoroughly. This document seems like I can added back without changes. 

As for your question, I didn't think about it before 🤔 however, does it work when you provide "/" as the base URL in `Remoting.createApi`?

**Comment by OnurGumus** [comment]
Thanks, it works. it points to "file:///" so it is ignored. I use the client.BaseAddress.ToString() which is saner. But it may confuse other people.

**Comment by Zaid-Ajaj** [comment]
> I use the client.BaseAddress.ToString() which is saner

@OnurGumus I'll keep it in mind when I re-upload the document. Old docs are still [here](https://github.com/Zaid-Ajaj/Fable.Remoting/tree/master/documentation) btw

**Comment by Zaid-Ajaj** [comment]
Done! Added back this document and explained how to use the latest API
