### ISSUE TITLE
Async<'T> does not send a request in production mode

### ISSUE THREAD

**Issue by Zaid-Ajaj** [Zaid-Ajaj/Fable.Remoting#32]
Remoting functions of type `Async<'T>` don't seem to send the request to server when serving the generated javascript bundle (in production mode) from the same server normally rather than from `webpack-dev-server`. 

I always ran integration tests in `webpack-dev-server` but production builds seem to affect the behaviour. @Nhowka can you reproduce this? If so, this could be a Fable problem as well

**Comment by Nhowka** [comment]
Found the problem. When in production, the name in minified, so it's not "Async" anymore... I'll try to find a workaround.
https://github.com/Zaid-Ajaj/Fable.Remoting/blob/master/Fable.Remoting.Client/Proxy.fs#L94

**Comment by Nhowka** [comment]
This one worked on my local tests

**Comment by Zaid-Ajaj** [comment]
Wow you are fast :heart: :heart: I had no idea how to fix this!!! I just ran the integration tests again and tests passed!

**Comment by Nhowka** [comment]
When I was checking the properties of the proxy I noticed that the `pureAsync` wasn't there instead of calling a just calling non working function. The workaround was a really lucky guess, I honestly had no hope it would work! 😅

But now it's as it should be, hardcoding the string was bad judgement.

**Comment by Zaid-Ajaj** [comment]
That guess was spot on! :smile: thanks agian :pray:
