### ISSUE TITLE
Paket versions mismatch

### ISSUE THREAD

**Issue by pkese** [Zaid-Ajaj/Fable.Remoting#41]
I'm having issues with installing `Fable.Remoting.Suave` alongside `Suave`:

    Paket failed with
    -> There was a version conflict during package resolution.
         Resolved packages:
          - Fable.Remoting.Suave 2.6.0
         Conflict detected:
          - Suave 2.3.0-beta3 requested package FSharp.Core: >= 4.0.0.1 < 4.0.1*
          - Fable.Remoting.Suave 2.6.0 requested package FSharp.Core: >= 4.3.4

I'm actually building for netstandard 2.0, but on ARM architecture (Rasblerry Pi). Not everything is polished for ARM yet.

Is there a reason for the upper limit on version of `FSharp.Core`?

**Comment by Zaid-Ajaj** [comment]
Hi @pkese it seems that Suave is being pulled down for net46 instead of the netstandard2.0 target. One solution I can think of is to pin the version of Suave in paket.dependencies `nuget Suave ~> 2.2.1` where `2.2.1` won't have that `>= 4.0.0.1 < 4.0.1` constraint. Another solution (I think) is to force the dependency group where Suave lives (in paket.dependencies) to use netstandard2.0, although I am not sure how to achieve this

> Is there a reason for the upper limit on version of FSharp.Core?

No, there isn't AFAIK, but that shouldn't be a problem

**Comment by pkese** [comment]
Uh, sorry. It is `Suave` that is limiting the upper version.
Closing the issue.

**Comment by pkese** [comment]
:)
We both replied at the same time.

Thanks for the hints. I'll try them.

**Comment by Zaid-Ajaj** [comment]
No problem :smile: Happy to help!
