### ISSUE TITLE
Client Proxy.fs does not set the "Credentials" Fetch request property

### ISSUE THREAD

**Issue by Elonon** [Zaid-Ajaj/Fable.Remoting#64]
The request properties sent to `GlobalFetch.fetch` [originally included](https://github.com/Zaid-Ajaj/Fable.Remoting/blob/6f39e2c783bf807a9609320a697e5dcea976c7ba/Fable.Remoting.Client/Proxy.fs#L188) the Credentials option. [The latest version does not](https://github.com/Zaid-Ajaj/Fable.Remoting/blob/2d55c3a30d76178c78bab8d50cb2624f54b54021/Fable.Remoting.Client/Proxy.fs#L112). That property [needs to be set to ensure cookies are included](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch) in the request.

It looks like it was just left out by mistake. I can send a PR if you want.

**Comment by Zaid-Ajaj** [comment]
Hi @Elonon, it seemed I removed too many stuff in the recent upgrade 😅 my bad! I have added it back in and published Client `v3.2.1` it should be available from nuget very soon 

However, I wonder why the cookies aren't being included because I explicitly [add them](https://github.com/Zaid-Ajaj/Fable.Remoting/blob/master/Fable.Remoting.Client/Proxy.fs#L99) in the request headers.

**Comment by Elonon** [comment]
Thanks for fixing that so quickly! 

Cookies with the `HTTPOnly` flag aren't visible to `document.cookie`. Most session/authentication cookies use this flag to prevent XSS.

[This page](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie) explains it better than I can.

**Comment by Zaid-Ajaj** [comment]
Thanks @Elonon for the reference, I will definitely check it out!
