### ISSUE TITLE
If you define an interface with `T seq` return type, Fable.Remoting doesn't seem to deserialize DUs properly.

### ISSUE THREAD

**Issue by AkosLukacs** [Zaid-Ajaj/Fable.Remoting#66]
Full repro here: https://github.com/AkosLukacs/fable-remoting-seq-type Just clone & run.

If you define an interface with `T seq` return type, Fable.Remoting doesn't seem to deserialize DUs properly. Deserialization works just fine with `T list`

```fsharp
// interface in Shared.fs
type ICounterApi =
    {
      test: unit -> Async<Dummyx list>
      testSeq: unit -> Async<Dummyx seq>
    }

// implementation in Server.fs.
let counterApi = {
    test = fun () -> async {
        return [
            {Id = 1; First = SimpleDU.FirstCase; Second = SimpleDU.SecondCase; Third = SimpleDU.ThirdCase; Complex = ComplexDU.B "test"}
        ]
    }
    testSeq = fun () -> async {
        return List.toSeq [
            {Id = 1; First = SimpleDU.FirstCase; Second = SimpleDU.SecondCase; Third = SimpleDU.ThirdCase; Complex = ComplexDU.B "testSeq"}
        ]
    }
}
```

Server response as seen on Network tab of the browser is same in both cases:
```json
[{"Id":1,"First":"FirstCase","Second":"SecondCase","Third":"ThirdCase","Complex":{"B":"test"}}]
[{"Id":1,"First":"FirstCase","Second":"SecondCase","Third":"ThirdCase","Complex":{"B":"testSeq"}}]
```

If you console log the result, shows different result for different interface definitions:

``` javascript
// GotTest data:
{​​
    Complex: Object { tag: 1, data: "test" }​​
    First: Object { tag: 0 }​​
    Id: 1​​
    Second: Object { tag: 1 }​​
    Third: Object { tag: 2 }
}

// GotTestSeq data:
{
    Complex: Object { B: "testSeq" }
    First: "FirstCase"    ​​
    Id: 1    ​​
    Second: "SecondCase"    ​​
    Third: "ThirdCase"
}
```

**Comment by Zaid-Ajaj** [comment]
Hello @AkosLukacs, thanks for the detailed report 

This is a known limitation of Fable's (1.x) internal `ofJson`, when you use `seq` where you mean "here is a generic sequence of elements", Fable doesn't know to which concrete type it should deserialize the sequence, should it be a list by default or an array etc. This issue is not specific to DU's but for DateTime's as well, see [Alfonso's comment here](https://github.com/fable-compiler/Fable/issues/1344#issuecomment-367619212) on the [issue](https://github.com/fable-compiler/Fable/issues/1344)

It is the same when you try to deserialize `ISomGenericeInterface<T>` with Json.NET, the deserializer doesn't know to which concrete implementation of `ISomGenericeInterface<T>` it should deserialize or which concrete implementations are available in the first place, `seq` is a special case where we can choose to default for arrays or lists but it wasn't implemented 

I will try to add this as a side note to the docs soon 

I will see if I can fix the issue when I convert the client to work with Fable 2 :smile:

**Comment by AkosLukacs** [comment]
@Zaid-Ajaj thank you for the detailed answer :)

Makes sense, a runtime warning (if possible) would be helpful. But I guess that's on fable-side of the world. Maybe Fable 2 will solve this issue.

**Comment by Zaid-Ajaj** [comment]
Fable 2 will not include any automatic Json conversion, instead it will be handled on third-party libraries, Fable.Remoting is planned to use [Fable.SimpleJson](https://github.com/Zaid-Ajaj/Fable.SimpleJson) where it is already working perfectly on Fable 2 beta, I just added `seq<'t>` conversion support with tests:
```fs
type Dummy = { first: int }
type DummySeq = DummySeq of Dummy seq 
type DummyList = DummyList of Dummy list 

testCase "List<'t> can be deserialized" <| fun test -> 
    [{ first = 10 }]
    |> DummyList
    |> Json.stringify
    |> Json.parseNativeAs<DummyList> 
    |> test.areEqual (DummyList [{ first = 10 }])
 
testCase "Seq<'t> can be deserialized" <| fun test -> 
    "[\"DummySeq\", [{ \"first\": 10 }]]"
    |> Json.parseNativeAs<DummySeq> 
    |> fun dummy -> 
        match dummy with 
        | DummySeq elems -> 
            match List.ofSeq elems with 
            | [ { first = 10 } ] -> test.pass()
            | _ -> test.fail() 

testCase "Seq<'t> can be serialized correctly" <| fun test -> 
    seq { yield { first = 10 } }
    |> DummySeq
    |> Json.stringify
    |> test.areEqual "[\"DummySeq\",[{\"first\":10}]]"
```
