### ISSUE TITLE
Can't find WebHostBuilder in Giraffe example

### ISSUE THREAD

**Issue by bratfizyk** [Zaid-Ajaj/Fable.Remoting#85]
Well... It's a minor thing, but I decided to ask anyway.

I tried following the manual step-by-step guide, but when I hit the section for [Giraffe](https://github.com/Zaid-Ajaj/Fable.Remoting#giraffe), the compiler complains that WebHostBuilder() is unknown. Where can I find it ?

**Comment by Zaid-Ajaj** [comment]
No worries, it is in `Microsoft.AspNetCore.Hosting` but you have to open the following namespaces too for the extension methods of the builder, see [this example](https://github.com/Zaid-Ajaj/Fable.Remoting/tree/master/Fable.Remoting.IntegrationTests/Server.Giraffe) from the integration tests sample:
```fs
open Microsoft.AspNetCore.Http
open Microsoft.AspNetCore.Builder
open Microsoft.AspNetCore.Hosting
open Microsoft.AspNetCore.Server.Kestrel
```
I didn't include them as to make the snippet smaller because I assumed you already had those if you start with a working Giraffe app, I guess I will add the whole snippet

**Comment by bratfizyk** [comment]
Cool, thanks - I have some experience with Suave, but this time I decided to be "cool and do something new" ;). 
+1 for your reasoning about keeping the snippets simple.
